### ISSUE TITLE
Output file with improved plate naming

### ISSUE THREAD

**Issue by daniel-biosyntia** [biosyntia/96wellReadR#8]
Current naming is mixing up submission IDs with experiment IDs.  Please find attached an image explaining the issue.

Desired output is:

JOB + Running_ID
experiment + plate
![Feedbatck_automatic_data_analysis](https://user-images.githubusercontent.com/53002748/166653728-c9ceb96b-e001-446f-ac9f-0bda2e4ab2bb.png)

**Comment by DavidL-H** [comment]
@daniel-biosyntia, the issue should now be fixed.
